// Generated by LiveScript 1.3.1
(function(){
  var Button, addClickingToAllButtons, addClickingToBigButtons, resetAllWhenLeaving, resetAllWhenEntering, BigButton;
  Button = (function(){
    Button.displayName = 'Button';
    var prototype = Button.prototype, constructor = Button;
    Button.buttons = [];
    Button.disableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.disable());
        }
      }
      return results$;
    };
    Button.enableOtherButtons = function(thisButton){
      var i$, ref$, len$, button, results$ = [];
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button !== thisButton && button.state !== 'done') {
          results$.push(button.enable());
        }
      }
      return results$;
    };
    Button.resetAll = function(){
      var i$, ref$, len$;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        (fn$.call(this, ref$[i$]));
      }
      function fn$(button){
        button.reset();
      }
    };
    Button.allButtonsClicked = function(){
      var i$, ref$, len$, button;
      for (i$ = 0, len$ = (ref$ = this.buttons).length; i$ < len$; ++i$) {
        button = ref$[i$];
        if (button.state !== 'done') {
          return false;
        }
      }
      return true;
    };
    function Button(dom){
      var this$ = this;
      this.dom = dom;
      this.state = 'enable';
      this.ballon = this.dom.find('.unread');
      this.ballon.addClass('hidden-ballon');
      this.dom.addClass('enable');
      this.dom.click(function(){
        if (this$.state === 'enable') {
          this$.constructor.disableOtherButtons(this$);
          this$.clicked();
          this$.getNumber();
        }
      });
      this.constructor.buttons.push(this);
    }
    prototype.getNumber = function(){
      var this$ = this;
      $.get('/hehe', function(number, status){
        if (this$.state === 'clicked') {
          this$.constructor.enableOtherButtons(this$);
          this$.done();
          this$.showNumberInBallon(number);
          BigButton.count(number);
          if (this$.constructor.allButtonsClicked() === true) {
            BigButton.changeBigButtonState();
          }
        }
      });
    };
    prototype.enable = function(){
      this.state = "enable";
      this.dom.removeClass("disable");
      this.dom.addClass("enable");
    };
    prototype.disable = function(){
      this.state = "disable";
      this.dom.removeClass("enable");
      this.dom.addClass("disable");
    };
    prototype.clicked = function(){
      this.state = "clicked";
      this.ballon.removeClass('hidden-ballon');
      this.ballon.addClass('waiting-ballon');
      this.ballon.text('...');
    };
    prototype.done = function(){
      this.state = "done";
      this.dom.removeClass("enable");
      this.dom.addClass("disable");
    };
    prototype.reset = function(){
      this.state = "enable";
      this.dom.removeClass('disable');
      this.dom.addClass('enable');
      this.ballon.removeClass(this.state);
      this.ballon.addClass('hidden-ballon');
      this.ballon.text('');
    };
    prototype.showNumberInBallon = function(number){
      this.ballon.text(number);
    };
    return Button;
  }());
  addClickingToAllButtons = function(){
    var i$, ref$, len$;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      (fn$.call(this, ref$[i$]));
    }
    function fn$(dom){
      var button;
      button = new Button($(dom));
    }
  };
  addClickingToBigButtons = function(){
    var dom, bigButton;
    dom = $('#info-bar');
    bigButton = new BigButton($(dom));
  };
  $(function(){
    addClickingToAllButtons();
    addClickingToBigButtons();
    resetAllWhenLeaving();
    resetAllWhenEntering();
  });
  resetAllWhenLeaving = function(){
    var all;
    all = $('#bottom-positioner');
    all.mouseleave(function(){
      BigButton.resetLargeButton();
      Button.resetAll();
    });
  };
  resetAllWhenEntering = function(){
    var all;
    all = $('#buttom-positoner');
    all.mouseenter(function(){
      BigButton.resetLargeButton();
      Button.resetAll();
    });
  };
  BigButton = (function(){
    BigButton.displayName = 'BigButton';
    var prototype = BigButton.prototype, constructor = BigButton;
    BigButton.number = 0;
    BigButton.resetLargeButton = function(){
      this.bigButton.reset();
    };
    BigButton.bigButton;
    BigButton.count = function(newNumber){
      this.number += parseInt(newNumber);
    };
    BigButton.changeBigButtonState = function(){
      this.bigButton.enable();
    };
    prototype.showNumberInBigButton = function(){
      this.showNumberContainer.text(this.constructor.number);
    };
    function BigButton(dom){
      var this$ = this;
      this.dom = dom;
      this.disable();
      this.showNumberContainer = this.dom.find('p');
      this.dom.click(function(){
        if (this$.state === 'enable') {
          this$.showNumberInBigButton();
          this$.disable();
        }
      });
      this.constructor.bigButton = this;
    }
    prototype.disable = function(){
      this.state = 'disable';
      this.dom.removeClass('enable');
      this.dom.addClass('disable');
    };
    prototype.enable = function(){
      this.state = 'enable';
      this.dom.removeClass('disable');
      this.dom.addClass('enable');
    };
    prototype.reset = function(){
      this.state = 'disable';
      this.dom.removeClass('enable');
      this.dom.addClass('disable');
      this.constructor.number = 0;
      this.showNumberContainer.text("");
    };
    return BigButton;
  }());
}).call(this);
